### ISSUE TITLE
Binary for RHEL based systems

### ISSUE THREAD

**Issue by coolboole** [Sysinternals/ProcMon-for-Linux#103]
Please, could you release a binary for RHEL, Fedora, Rocky, Alma and CentOS based systems?

**Comment by densanx** [comment]
+

**Comment by Zeroes1** [comment]
+

**Comment by MarioHewardt** [comment]
Hi - Apologies for the delay in response on this one. At the moment, Procmon for Linux does not support Fedora based systems. We are working to change that. Please stay tuned.

**Comment by emiliesecherre** [comment]
I see the same package you ask to install for procmol ubuntu here : https://packages.microsoft.com/config/centos/7/, does Procmon work with Centos now ?

**Comment by MarioHewardt** [comment]
Hi - RHEL package is now available with the latest changes. Please give it a try and let us know!
