### ISSUE TITLE
Error on 'make' on Arch

### ISSUE THREAD

**Issue by abdulbadii** [Sysinternals/ProcMon-for-Linux#109]
Make going at: 

```
[ 32%] Building CXX object _deps/bcc-build/src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/loader.cc.o

In file included from /usr/include/llvm/Support/SwapByteOrder.h:17,
                 from /usr/include/llvm/ADT/Hashing.h:49,
                 from /usr/include/clang/Basic/CustomizableOptional.h:12,
                 from /usr/include/clang/Basic/DirectoryEntry.h:17,
                 from /usr/include/clang/Basic/FileManager.h:17,
                 from /ProcMon-for-Linux-1.0.1/build/_deps/bcc-src/src/cc/frontends/clang/loader.cc:35:
/usr/include/llvm/ADT/bit.h:64:56: error: 'is_integral_v' is not a member of 'std'; did you mean 'is_integral'?
   64 | template <typename T, typename = std::enable_if_t<std::is_integral_v<T>>>

```

and likewise `is_unsigned_v`
accumulate to  many errors of such kinds

Any clear thought on such ?

**Comment by MarioHewardt** [comment]
Hi - at the moment Procmon for Linux supports only Ubuntu 20.04. We are working to extend the supported distros. Please stay tuned.

**Comment by abdulbadii** [comment]
But I meant it really failed due to only difference in Linux kind,
would shed a bit light comparison of each working mechanism ?

**Comment by MarioHewardt** [comment]
Hi - Procmon for Linux depends on an externally dependency (BCC) that we build during our build process. In the case above, it is BCC that is failing to build. I'm not sure as to why it's failing but with the work we are doing, we are moving away from BCC.
