### ISSUE TITLE
Syscall table uses hardcoded numbers

### ISSUE THREAD

**Issue by lpereira** [Sysinternals/ProcMon-for-Linux#15]
Syscall numbers vary between different architectures, so[ tables like this won't be portable](https://github.com/microsoft/ProcMon-for-Linux/blob/57eca030ef4f397680f0af9a61febaa21f0bc962/src/tracer/ebpf/syscall_schema.cpp#L21) for arches other than x86_64.

These tables can be built by running a script like this during build time:

```sh
echo "#include <sys/syscall.h>" | \
    cpp -dM | \
    grep '^#define __NR_' | \
    sed -r -n -e 's/^\#define[ \t]+__NR_([a-z0-9_]+)[ \t]+([0-9]+)(.*)/ [\2] = "\1",/p'
```

Which will produce something like:

```
 [247] = "waitid",
 [75] = "fdatasync",
 [245] = "mq_getsetattr",
 [204] = "sched_getaffinity",
 [42] = "connect",
 [281] = "epoll_pwait",
 [175] = "init_module",
 [176] = "delete_module",
 [258] = "mkdirat",
 [130] = "rt_sigsuspend",
 [257] = "openat",
(...)
```

(It can be easily tweaked to produce the inverted table, too.)

Calling `cpp` directly might not be the best thing to do, however, especially if you want to prepare this for cross-compilation.  Should be possible to perform this pipeline mostly in CMake, though.

**Comment by MarioHewardt** [comment]
Hi - We've removed the dependency on BCC (and removed static syscall list) and updated our build instructions. Please give it a go and let us know.
