### ISSUE TITLE
bcc fails to build on rpi 10 (buster)

### ISSUE THREAD

**Issue by pidloop** [Sysinternals/ProcMon-for-Linux#18]
On Raspbian GNU/Linux 10 (buster) near the end of making bcc I get this message:

`[ 95%] Building CXX object tests/cc/CMakeFiles/test_libbcc.dir/test_usdt_args.cc.o
In file included from /home/pi/bcc/tests/cc/test_usdt_args.cc:19:
/home/pi/bcc/tests/cc/test_usdt_args.cc: In function 'void ____C_A_T_C_H____T_E_S_T____55()':
/home/pi/bcc/tests/cc/test_usdt_args.cc:67:14: error: 'parser' was not declared in this scope
     REQUIRE(!parser.parse(&arg));
`

**Comment by MarioHewardt** [comment]
Thanks for the report. We haven't really tested building bcc for Raspian. I would suggest opening an issue on the iovisor/bcc repo.
