### ISSUE TITLE
Upgrade to latest BCC version to support new capabilities.

### ISSUE THREAD

**Issue by MarioHewardt** [Sysinternals/ProcMon-for-Linux#2]

**Comment by GingerGraham** [comment]
Will moving to the new BCC support other distros too?  Particularly I'm thinking of RHEL7 and 8?  Or is other work required for these distros?

**Comment by jahabibi** [comment]
@GingerGraham Upgrading BCC unfortunately does not unblock RHEL7 and RHEL8 due to underlying issues of BCC on RHEL.

Closing issue as Procmon 1.0.1 ships with latest version of BCC.
