### ISSUE TITLE
Procmon Build Fails

### ISSUE THREAD

**Issue by mbluett88** [Sysinternals/ProcMon-for-Linux#26]
In steps 2 & 3, the make fails because FlexLexer.h is missing.

**Comment by mbluett88** [comment]
Also bpf.h cannot be found.

**Comment by jahabibi** [comment]
@mbluett88 Can you provide information of what your environment is? Specifically what `lsb_release -a` and `uname -r` return?

**Comment by jamespeace** [comment]
I got the same problem.

`dennis@dennis-XPS-13-9370:~/workspace/Procmon-for-Linux/build$make
[ 78%] Building CXX object src/configuration/CMakeFiles/configuration-static.dir/procmon_configuration.cpp.o
In file included from /home/dennis/workspace/Procmon-for-Linux/src/configuration/procmon_configuration.h:21,
                 from /home/dennis/workspace/Procmon-for-Linux/src/configuration/procmon_configuration.cpp:4:
/home/dennis/workspace/Procmon-for-Linux/src/configuration/../tracer/ebpf/ebpf_tracer_engine.h:6:10: fatal error: bcc/BPF.h: No such file or directory
 #include <bcc/BPF.h>
          ^~~~~~~~~~~
compilation terminated.
src/configuration/CMakeFiles/configuration-static.dir/build.make:81: recipe for target 'src/configuration/CMakeFiles/configuration-static.dir/procmon_configuration.cpp.o' failed
make[2]: *** [src/configuration/CMakeFiles/configuration-static.dir/procmon_configuration.cpp.o] Error 1
CMakeFiles/Makefile2:2532: recipe for target 'src/configuration/CMakeFiles/configuration-static.dir/all' failed
make[1]: *** [src/configuration/CMakeFiles/configuration-static.dir/all] Error 2
Makefile:181: recipe for target 'all' failed
make: *** [all] Error 2`

`dennis@dennis-XPS-13-9370:~/workspace/Procmon-for-Linux$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
dennis@dennis-XPS-13-9370:~/workspace/Procmon-for-Linux$ uname -r
5.3.0-62-generic`

**Comment by jamespeace** [comment]
Got the same error.

```
dennis@dennis-XPS-13-9370:~/workspace/Procmon-for-Linux/build$make
[ 78%] Building CXX object src/configuration/CMakeFiles/configuration-static.dir/procmon_configuration.cpp.o
In file included from /home/dennis/workspace/Procmon-for-Linux/src/configuration/procmon_configuration.h:21,
                 from /home/dennis/workspace/Procmon-for-Linux/src/configuration/procmon_configuration.cpp:4:
/home/dennis/workspace/Procmon-for-Linux/src/configuration/../tracer/ebpf/ebpf_tracer_engine.h:6:10: fatal error: bcc/BPF.h: No such file or directory
 #include <bcc/BPF.h>
          ^~~~~~~~~~~
compilation terminated.
src/configuration/CMakeFiles/configuration-static.dir/build.make:81: recipe for target 'src/configuration/CMakeFiles/configuration-static.dir/procmon_configuration.cpp.o' failed
make[2]: *** [src/configuration/CMakeFiles/configuration-static.dir/procmon_configuration.cpp.o] Error 1
CMakeFiles/Makefile2:2532: recipe for target 'src/configuration/CMakeFiles/configuration-static.dir/all' failed
make[1]: *** [src/configuration/CMakeFiles/configuration-static.dir/all] Error 2
Makefile:181: recipe for target 'all' failed
make: *** [all] Error 2
```

```
dennis@dennis-XPS-13-9370:~/workspace/Procmon-for-Linux$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```
```
dennis@dennis-XPS-13-9370:~/workspace/Procmon-for-Linux$ uname -r
5.3.0-62-generic
```

**Comment by MarioHewardt** [comment]
Hi - We've removed the dependency on BCC and updated our build instructions. Please give it a go and let us know.
