### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [Sysinternals/ProcMon-for-Linux#30]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the function “safeDelete”](https://github.com/microsoft/ProcMon-for-Linux/blob/70d5196efce7e4e625912ceadccadbcc42f83af4/src/logging/easylogging%2B%2B.h#L853 "Update candidate").

**Comment by MarioHewardt** [comment]
Please log an issue with EasyLogging++ which is the dependent logging framework.

**Comment by elfring** [comment]
Would you like to [influence the software evolution any further](https://github.com/amrayn/easyloggingpp/issues/789 "Update suggestion")?
