### ISSUE TITLE
bcc 0.10.0 can't be built in Arch Linux now

### ISSUE THREAD

**Issue by lingsamuel** [Sysinternals/ProcMon-for-Linux#36]
> some distros already packaging clang 10 (checked fedora and arch) no longer
> ship all the individual libclang*.so component libraries.
> Instead, clang from 9.0 onwards provides a new lib, libclang-cpp.so, which
> includes everything we need.

ref commit: https://github.com/iovisor/bcc/commit/1599c2ef8206988d5df7eeadc3c5138c006ac245#diff-af3b638bc2a3e6c650974192a53c7291

**Comment by MarioHewardt** [comment]
This is a BCC dependency not procmon.
