### ISSUE TITLE
libclang_frontend issue when I try to compile

### ISSUE THREAD

**Issue by dragonxtek** [Sysinternals/ProcMon-for-Linux#41]
After cmake finished in both, bcc and procmon, I try to compile them, but both stop here:

> /usr/include/c++/8/bits/stl_pair.h:208:12: note: ‘struct std::pair<void*, long unsigned int>’ declared here
     struct pair
            ^~~~
Linking CXX static library libclang_frontend.a
Built target clang_frontend
make: *** [Makefile:163: all] Error 2

I have Ubuntu 18.10 with cmake 1.15

**Comment by MarioHewardt** [comment]
To build procmon, it requires CMAKE 3.14 or higher.
