### ISSUE TITLE
error: 'BPF_MAP_TYPE_QUEUE' was not declared in this scope

### ISSUE THREAD

**Issue by TimelifeCzy** [Sysinternals/ProcMon-for-Linux#60]
`
root@ubuntu:~/Procmon-for-Linux/build# cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Curses: /usr/lib/x86_64-linux-gnu/libcurses.so
CMake Deprecation Warning at build/_deps/bcc-src/CMakeLists.txt:3 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Latest recognized Git tag is -128-NOTFOUND
-- Git HEAD is b35d4cc583ec747dfc18dabef974d1a6e5a3eeb0
-- Revision is 128-NOTFOUND-b35d4cc5
-- Performing Test HAVE_NO_PIE_FLAG
-- Performing Test HAVE_NO_PIE_FLAG - Success
-- Performing Test HAVE_REALLOCARRAY_SUPPORT
-- Performing Test HAVE_REALLOCARRAY_SUPPORT - Success
-- Found LLVM: /usr/lib/llvm-6.0/include 6.0.0
-- Found BISON: /usr/bin/bison (found version "3.0.4")
-- Found FLEX: /usr/bin/flex (found version "2.6.4")
-- Found LibElf: /usr/lib/x86_64-linux-gnu/libelf.so
-- Performing Test ELF_GETSHDRSTRNDX
-- Performing Test ELF_GETSHDRSTRNDX - Success
-- Using static-libstdc++
-- Could NOT find LuaJIT (missing: LUAJIT_LIBRARIES LUAJIT_INCLUDE_DIR)
CMake Warning at build/_deps/bcc-src/tests/python/CMakeLists.txt:10 (message):
  Recommended test program 'netperf' not found

CMake Warning at build/_deps/bcc-src/tests/python/CMakeLists.txt:16 (message):
  Recommended test program 'iperf' or 'iperf3' not found

-- Configuring done
-- Generating done
-- Build files have been written to: /root/Procmon-for-Linux/build
root@ubuntu:~/Procmon-for-Linux/build# make
[  0%] Building CXX object src/logging/CMakeFiles/logging-static.dir/easylogging++.cc.o
[  3%] Linking CXX static library liblogging-static.a
[  3%] Built target logging-static
[  3%] Building C object CMakeFiles/sqlite3-static.dir/vendor/sqlite3/sqlite3.c.o
[  6%] Linking C static library libsqlite3-static.a
[  6%] Built target sqlite3-static
[  6%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bpf-static.dir/libbpf.c.o
[  6%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bpf-static.dir/perf_reader.c.o
[ 10%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bpf-static.dir/libbpf/src/bpf.c.o
[ 10%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bpf-static.dir/libbpf/src/bpf_prog_linfo.c.o
[ 10%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bpf-static.dir/libbpf/src/btf.c.o
[ 13%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bpf-static.dir/libbpf/src/btf_dump.c.o
[ 13%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bpf-static.dir/libbpf/src/hashmap.c.o
[ 13%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bpf-static.dir/libbpf/src/libbpf.c.o
[ 17%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bpf-static.dir/libbpf/src/libbpf_errno.c.o
[ 17%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bpf-static.dir/libbpf/src/libbpf_probes.c.o
[ 17%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bpf-static.dir/libbpf/src/netlink.c.o
[ 20%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bpf-static.dir/libbpf/src/nlattr.c.o
[ 20%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bpf-static.dir/libbpf/src/ringbuf.c.o
[ 20%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bpf-static.dir/libbpf/src/str_error.c.o
[ 24%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bpf-static.dir/libbpf/src/xsk.c.o
[ 24%] Linking C static library libbcc_bpf.a
[ 24%] Built target bpf-static
[ 27%] Building CXX object _deps/bcc-build/src/cc/CMakeFiles/bcc-loader-static.dir/bcc_syms.cc.o
[ 27%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bcc-loader-static.dir/bcc_elf.c.o
[ 27%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bcc-loader-static.dir/bcc_perf_map.c.o
[ 31%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bcc-loader-static.dir/bcc_proc.c.o
[ 31%] Building CXX object _deps/bcc-build/src/cc/CMakeFiles/bcc-loader-static.dir/common.cc.o
[ 31%] Linking CXX static library libbcc-loader-static.a
[ 31%] Built target bcc-loader-static
[ 31%] Building CXX object _deps/bcc-build/src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/loader.cc.o
In file included from /usr/lib/llvm-6.0/include/clang/AST/RecursiveASTVisitor.h:24:0,
                 from /root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/frontends/clang/b_frontend_action.h:23,
                 from /root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/frontends/clang/loader.cc:57:
/usr/lib/llvm-6.0/include/clang/AST/DeclOpenMP.h:97:1: warning: multi-line comment [-Wcomment]
 /// #pragma omp declare reduction (foo : int,float : omp_out += omp_in) \
 ^
[ 31%] Building CXX object _deps/bcc-build/src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/b_frontend_action.cc.o
In file included from /usr/lib/llvm-6.0/include/clang/AST/RecursiveASTVisitor.h:24:0,
                 from /root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/frontends/clang/b_frontend_action.h:23,
                 from /root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/frontends/clang/b_frontend_action.cc:31:
/usr/lib/llvm-6.0/include/clang/AST/DeclOpenMP.h:97:1: warning: multi-line comment [-Wcomment]
 /// #pragma omp declare reduction (foo : int,float : omp_out += omp_in) \
 ^
[ 34%] Building CXX object _deps/bcc-build/src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/tp_frontend_action.cc.o
In file included from /usr/lib/llvm-6.0/include/clang/AST/RecursiveASTVisitor.h:24:0,
                 from /root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/frontends/clang/tp_frontend_action.h:23,
                 from /root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/frontends/clang/tp_frontend_action.cc:32:
/usr/lib/llvm-6.0/include/clang/AST/DeclOpenMP.h:97:1: warning: multi-line comment [-Wcomment]
 /// #pragma omp declare reduction (foo : int,float : omp_out += omp_in) \
 ^
[ 34%] Building CXX object _deps/bcc-build/src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/kbuild_helper.cc.o
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/frontends/clang/kbuild_helper.cc:80:3: warning: multi-line comment  -Wcomment]
   // USERINCLUDE    := \
   ^
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/frontends/clang/kbuild_helper.cc:89:3: warning: multi-line comment  -Wcomment]
   // LINUXINCLUDE    := \
   ^
[ 34%] Building CXX object _deps/bcc-build/src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/__/__/common.cc.o
[ 34%] Linking CXX static library libclang_frontend.a
[ 34%] Built target clang_frontend
[ 34%] Building CXX object _deps/bcc-build/src/cc/api/CMakeFiles/api-static.dir/BPF.cc.o
In file included from /root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPF.cc:32:0:
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/bcc_exception.h: In member function ‘ebpf::StatusTuple ebpf::BPF::detach_raw_tracepoint_event(const string&, ebpf::open_probe_t&)’:
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/bcc_exception.h:24:7: warning: ‘__stp.ebpf::StatusTuple::code_’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 class StatusTuple {
       ^~~~~~~~~~~
[ 37%] Building CXX object _deps/bcc-build/src/cc/api/CMakeFiles/api-static.dir/BPFTable.cc.o
[ 37%] Linking CXX static library libapi-static.a
[ 37%] Built target api-static
[ 37%] Building CXX object _deps/bcc-build/src/cc/usdt/CMakeFiles/usdt-static.dir/usdt_args.cc.o
[ 41%] Building CXX object _deps/bcc-build/src/cc/usdt/CMakeFiles/usdt-static.dir/usdt.cc.o
[ 41%] Linking CXX static library libusdt-static.a
[ 41%] Built target usdt-static
[ 41%] [BISON][Parser] Building parser with bison 3.0.4
parser.yy:19.9-17: warning: deprecated directive, use ‘%define api.namespace ebpf::cc’ [-Wdeprecated]
 %define namespace "ebpf::cc"
         ^^^^^^^^^
parser.yy:19.9-17: warning: %define variable 'api.namespace' requires '{...}' values [-Wdeprecated]
 %define namespace "ebpf::cc"
         ^^^^^^^^^
parser.yy:20.9-25: warning: %define variable 'parser_class_name' requires '{...}' values [-Wdeprecated]
 %define parser_class_name "BisonParser"
         ^^^^^^^^^^^^^^^^^
[ 44%] [FLEX][Lexer] Building scanner with flex 2.6.4
lexer.ll:110: warning, -s option given but default rule can be matched
[ 44%] Building CXX object _deps/bcc-build/src/cc/frontends/b/CMakeFiles/b_frontend.dir/loader.cc.o
[ 44%] Building CXX object _deps/bcc-build/src/cc/frontends/b/CMakeFiles/b_frontend.dir/codegen_llvm.cc.o
[ 48%] Building CXX object _deps/bcc-build/src/cc/frontends/b/CMakeFiles/b_frontend.dir/node.cc.o
[ 48%] Building CXX object _deps/bcc-build/src/cc/frontends/b/CMakeFiles/b_frontend.dir/parser.cc.o
[ 48%] Building CXX object _deps/bcc-build/src/cc/frontends/b/CMakeFiles/b_frontend.dir/printer.cc.o
[ 48%] Building CXX object _deps/bcc-build/src/cc/frontends/b/CMakeFiles/b_frontend.dir/type_check.cc.o
[ 51%] Building CXX object _deps/bcc-build/src/cc/frontends/b/CMakeFiles/b_frontend.dir/parser.yy.cc.o
[ 51%] Building CXX object _deps/bcc-build/src/cc/frontends/b/CMakeFiles/b_frontend.dir/lexer.ll.cc.o
[ 51%] Linking CXX static library libb_frontend.a
[ 51%] Built target b_frontend
[ 51%] Building CXX object _deps/bcc-build/src/cc/CMakeFiles/bcc-static.dir/bcc_common.cc.o
[ 51%] Building CXX object _deps/bcc-build/src/cc/CMakeFiles/bcc-static.dir/bpf_module.cc.o
In file included from /usr/lib/llvm-6.0/include/clang/AST/RecursiveASTVisitor.h:24:0,
                 from /root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/frontends/clang/b_frontend_action.h:23,
                 from /root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/bpf_module.cc:43:
/usr/lib/llvm-6.0/include/clang/AST/DeclOpenMP.h:97:1: warning: multi-line comment [-Wcomment]
 /// #pragma omp declare reduction (foo : int,float : omp_out += omp_in) \
 ^
[ 55%] Building CXX object _deps/bcc-build/src/cc/CMakeFiles/bcc-static.dir/bcc_btf.cc.o
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/bcc_btf.cc: In member function ‘int ebpf::BTF::get_btf_info(const char*, void**, unsigned int*, unsigned int*, void**, unsigned int*, unsigned int*)’:
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/bcc_btf.cc:316:33: warning: ‘int btf_ext__reloc_func_info(const btf*, const btf_ext*, const char*, __u32, void**, __u32*)’ is deprecated: btf_ext__reloc_func_info was never meant as a public API and has wrong assumptions embedded in it; it will be removed in the future libbpf versions [-Wdeprecated-declarations]
         func_info, func_info_cnt);
                                 ^
In file included from /root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/bcc_libbpf_inc.h:9:0,
                 from /root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/bcc_btf.cc:22:
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/libbpf/src/btf.h:80:5: note: declared here
 int btf_ext__reloc_func_info(const struct btf *btf,
     ^~~~~~~~~~~~~~~~~~~~~~~~
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/bcc_btf.cc:323:33: warning: ‘int btf_ext__reloc_line_info(const btf*, const btf_ext*, const char*, __u32, void**, __u32*)’ is deprecated: btf_ext__reloc_line_info was never meant as a public API and has wrong assumptions embedded in it; it will be removed in the future libbpf versions [-Wdeprecated-declarations]
         line_info, line_info_cnt);
                                 ^
In file included from /root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/bcc_libbpf_inc.h:9:0,
                 from /root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/bcc_btf.cc:22:
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/libbpf/src/btf.h:85:5: note: declared here
 int btf_ext__reloc_line_info(const struct btf *btf,
     ^~~~~~~~~~~~~~~~~~~~~~~~
[ 55%] Building CXX object _deps/bcc-build/src/cc/CMakeFiles/bcc-static.dir/exported_files.cc.o
[ 55%] Building CXX object _deps/bcc-build/src/cc/CMakeFiles/bcc-static.dir/bcc_debug.cc.o
[ 58%] Building CXX object _deps/bcc-build/src/cc/CMakeFiles/bcc-static.dir/bpf_module_rw_engine.cc.o
[ 58%] Building CXX object _deps/bcc-build/src/cc/CMakeFiles/bcc-static.dir/table_storage.cc.o
[ 58%] Building CXX object _deps/bcc-build/src/cc/CMakeFiles/bcc-static.dir/shared_table.cc.o
[ 62%] Building CXX object _deps/bcc-build/src/cc/CMakeFiles/bcc-static.dir/bpffs_table.cc.o
[ 62%] Building CXX object _deps/bcc-build/src/cc/CMakeFiles/bcc-static.dir/json_map_decl_visitor.cc.o
In file included from /usr/lib/llvm-6.0/include/clang/AST/RecursiveASTVisitor.h:24:0,
                 from /root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/json_map_decl_visitor.cc:22:
/usr/lib/llvm-6.0/include/clang/AST/DeclOpenMP.h:97:1: warning: multi-line comment [-Wcomment]
 /// #pragma omp declare reduction (foo : int,float : omp_out += omp_in) \
 ^
[ 62%] Building CXX object _deps/bcc-build/src/cc/CMakeFiles/bcc-static.dir/common.cc.o
[ 65%] Building CXX object _deps/bcc-build/src/cc/CMakeFiles/bcc-static.dir/usdt/usdt.cc.o
[ 65%] Building CXX object _deps/bcc-build/src/cc/CMakeFiles/bcc-static.dir/usdt/usdt_args.cc.o
[ 65%] Building CXX object _deps/bcc-build/src/cc/CMakeFiles/bcc-static.dir/bcc_syms.cc.o
[ 65%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bcc-static.dir/bcc_elf.c.o
[ 68%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bcc-static.dir/bcc_perf_map.c.o
[ 68%] Building C object _deps/bcc-build/src/cc/CMakeFiles/bcc-static.dir/bcc_proc.c.o
[ 68%] Linking CXX static library libbcc.a
[ 68%] Built target bcc-static
[ 72%] Building CXX object src/common/CMakeFiles/common-static.dir/printable.cpp.o
[ 72%] Building CXX object src/common/CMakeFiles/common-static.dir/cli_utils.cpp.o
[ 72%] Linking CXX static library libcommon-static.a
[ 72%] Built target common-static
[ 75%] Building CXX object src/configuration/CMakeFiles/configuration-static.dir/procmon_configuration.cpp.o
In file included from /root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPF.h:25:0,
                 from /root/Procmon-for-Linux/src/configuration/../tracer/ebpf/ebpf_tracer_engine.h:6,
                 from /root/Procmon-for-Linux/src/configuration/procmon_configuration.h:21,
                 from /root/Procmon-for-Linux/src/configuration/procmon_configuration.cpp:4:
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPFTable.h: In constructor ‘ebpf::BPFQueueStackTable<ValueType>::BPFQueueStackTable(const ebpf::TableDesc&)’:
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPFTable.h:169:22: error: ‘BPF_MAP_TYPE_QUEUE’ was not declared in this scope
     if (desc.type != BPF_MAP_TYPE_QUEUE &&
                      ^~~~~~~~~~~~~~~~~~
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPFTable.h:169:22: note: suggested alternative: ‘BPF_MAP_TYPE_CPUMAP’
     if (desc.type != BPF_MAP_TYPE_QUEUE &&
                      ^~~~~~~~~~~~~~~~~~
                      BPF_MAP_TYPE_CPUMAP
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPFTable.h:170:22: error: ‘BPF_MAP_TYPE_STACK’ was not declared in this scope
         desc.type != BPF_MAP_TYPE_STACK)
                      ^~~~~~~~~~~~~~~~~~
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPFTable.h:170:22: note: suggested alternative: ‘BPF_MAP_TYPE_HASH’
         desc.type != BPF_MAP_TYPE_STACK)
                      ^~~~~~~~~~~~~~~~~~
                      BPF_MAP_TYPE_HASH
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPFTable.h: At global scope:
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPFTable.h:392:54: error: field ‘trace’ has incomplete type ‘bpf_stack_build_id [127]’
   struct bpf_stack_build_id trace[BPF_MAX_STACK_DEPTH];
                                                      ^
In file included from /root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPFTable.h:30:0,
                 from /root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPF.h:25,
                 from /root/Procmon-for-Linux/src/configuration/../tracer/ebpf/ebpf_tracer_engine.h:6,
                 from /root/Procmon-for-Linux/src/configuration/procmon_configuration.h:21,
                 from /root/Procmon-for-Linux/src/configuration/procmon_configuration.cpp:4:
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/bcc_syms.h:81:38: note: forward declaration of ‘struct bpf_stack_build_id’
                               struct bpf_stack_build_id *trace,
                                      ^~~~~~~~~~~~~~~~~~
In file included from /root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPF.h:25:0,
                 from /root/Procmon-for-Linux/src/configuration/../tracer/ebpf/ebpf_tracer_engine.h:6,
                 from /root/Procmon-for-Linux/src/configuration/procmon_configuration.h:21,
                 from /root/Procmon-for-Linux/src/configuration/procmon_configuration.cpp:4:
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPFTable.h: In constructor ‘ebpf::BPFSkStorageTable<ValueType>::BPFSkStorageTable(const ebpf::TableDesc&)’:
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPFTable.h:509:22: error: ‘BPF_MAP_TYPE_SK_STORAGE’ was not declared in this scope
     if (desc.type != BPF_MAP_TYPE_SK_STORAGE)
                      ^~~~~~~~~~~~~~~~~~~~~~~
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPFTable.h:509:22: note: suggested alternative: ‘BPF_MAP_TYPE_STACK_TRACE’
     if (desc.type != BPF_MAP_TYPE_SK_STORAGE)
                      ^~~~~~~~~~~~~~~~~~~~~~~
                      BPF_MAP_TYPE_STACK_TRACE
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPFTable.h: In constructor ‘ebpf::BPFCgStorageTable<ValueType>::BPFCgStorageTable(const ebpf::TableDesc&)’:
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPFTable.h:538:22: error: ‘BPF_MAP_TYPE_CGROUP_STORAGE’ was not declared in this scope
     if (desc.type != BPF_MAP_TYPE_CGROUP_STORAGE)
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPFTable.h:538:22: note: suggested alternative: ‘BPF_MAP_TYPE_CGROUP_ARRAY’
     if (desc.type != BPF_MAP_TYPE_CGROUP_STORAGE)
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                      BPF_MAP_TYPE_CGROUP_ARRAY
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPFTable.h: In constructor ‘ebpf::BPFPercpuCgStorageTable<ValueType>::BPFPercpuCgStorageTable(const ebpf::TableDesc&)’:
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPFTable.h:564:22: error: ‘BPF_MAP_TYPE_PERCPU_CGROUP_STORAGE’ was not declared in this scope
     if (desc.type != BPF_MAP_TYPE_PERCPU_CGROUP_STORAGE)
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/Procmon-for-Linux/build/_deps/bcc-src/src/cc/api/BPFTable.h:564:22: note: suggested alternative: ‘BPF_MAP_TYPE_PERCPU_ARRAY’
     if (desc.type != BPF_MAP_TYPE_PERCPU_CGROUP_STORAGE)
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                      BPF_MAP_TYPE_PERCPU_ARRAY
src/configuration/CMakeFiles/configuration-static.dir/build.make:75: recipe for target 'src/configuration/CMakeFiles/configuration-static.dir/procmon_configuration.cpp.o' failed
make[2]: *** [src/configuration/CMakeFiles/configuration-static.dir/procmon_configuration.cpp.o] Error 1
CMakeFiles/Makefile2:2539: recipe for target 'src/configuration/CMakeFiles/configuration-static.dir/all' failed
make[1]: *** [src/configuration/CMakeFiles/configuration-static.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
`

`
root@ubuntu:~/Procmon-for-Linux/build# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
`

ProcMon Version: git clone https://github.com/Microsoft/Procmon-for-Linux

**Comment by TimelifeCzy** [comment]
Ask for help~

**Comment by TimelifeCzy** [comment]
update new Bcc Success~
https://github.com/iovisor/bcc/releases

**Comment by QGB** [comment]
same problem .
@TimelifeCzy 

How to update bcc ?

**Comment by antonio-petricca** [comment]
Same for me!
