### ISSUE TITLE
Support non-LTS distributions

### ISSUE THREAD

**Issue by jdrch** [Sysinternals/ProcMon-for-Linux#63]
Procmon seems to target Ubuntu 18.04 and 20.04 exclusively. Some of us, like myself, are running shorter release cycle distros. I'm asking that support be added for these too.

**Comment by MarioHewardt** [comment]
Should work just fine on the non-LTS distros, however, testing and release management is only on the LTS versions.

**Comment by jdrch** [comment]
I imagine that's the case, but the repo is configured to return packages for LTS versions only. If you install the repo on a non-LTS version, e.g. 20.10, `# apt install procmon` will not find any package by that name.

**Comment by MarioHewardt** [comment]
Duplicate of #70
