### ISSUE TITLE
Build fails on Debian 10 @ "fatal error: FlexLexer.h: No such file or directory"

### ISSUE THREAD

**Issue by AeonEternum** [Sysinternals/ProcMon-for-Linux#65]
Here's the output:

> [ 41%] Building CXX object _deps/bcc-build/src/cc/frontends/b/CMakeFiles/b_frontend.dir/loader.cc.o
> In file included from /home/USER/Procmon-for-Linux/build/_deps/bcc-src/src/cc/frontends/b/parser.h:21,
>                  from /home/USER/Procmon-for-Linux/build/_deps/bcc-src/src/cc/frontends/b/loader.cc:18:
> /home/USER/Procmon-for-Linux/build/_deps/bcc-src/src/cc/frontends/b/lexer.h:22:10: fatal error: FlexLexer.h: No such file or directory
>  #include <FlexLexer.h>
>           ^~~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [_deps/bcc-build/src/cc/frontends/b/CMakeFiles/b_frontend.dir/build.make:87: _deps/bcc-build/src/cc/frontends/b/CMakeFiles/b_frontend.dir/loader.cc.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1123: _deps/bcc-build/src/cc/frontends/b/CMakeFiles/b_frontend.dir/all] Error 2
> make: *** [Makefile:166: all] Error 2

> USER@HOST:~/Procmon-for-Linux/build$ flex --version
> flex 2.6.4

Any ideas how to resolve this?

Thanks

Cheers, Aeon

**Comment by crafter999** [comment]
You need Install the flex package using the following command `apt-get install libfl-dev`

**Comment by AeonEternum** [comment]
Thanks! That helped. No idea why the package didn't get installed properly with the rest of the dependencies.
