### ISSUE TITLE
WSL2 Ubuntu 20.04: Exception is thrown

### ISSUE THREAD

**Issue by valsamis-d** [Sysinternals/ProcMon-for-Linux#91]
Hi,

I followed the steps below:

```
wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
```

and then

```
sudo apt-get update
sudo apt-get install procmon
```

but when I do `sudo procmon` I get the following runtime error:

![image](https://user-images.githubusercontent.com/17590539/182327988-b13407b8-416e-4ffd-adb6-3a053679ac02.png)

Thank you
Dimitrios

**Comment by valsamis-d** [comment]
@MarioHewardt tried the above, and now I get the following RTE:

![image](https://user-images.githubusercontent.com/17590539/182439568-6cc7909d-ff46-4faa-bdcd-a8fdab15c1c0.png)

**Comment by MarioHewardt** [comment]
Ah, with WSL2 it looks like you will need to enable kernel headers. Please look over at https://github.com/microsoft/WSL2-Linux-Kernel for build instructions.

**Comment by nopa12** [comment]
try this to fix the kernel headers:
https://gist.github.com/nopa12/c216d12d7ae0180d14307df3d95f37e4#easy-solution
